.gitignore, Gruntfile.js, README.md, package.json
Fixes #20.
GRUNT :bomb: 
@dannycoates r?
=> chore(l10n): setup extraction script for l10n

config.js, mailer.js, templates/index.js, templates/unlock.html, templates/unlock.txt, test/mail_helper.js
A combination of @rfk's PR #17 and @rfeeley's copy.
fixes #16 
Goes along with:
* https://github.com/mozilla/fxa-auth-db-server/pull/123
* https://github.com/mozilla/fxa-auth-db-mem/pull/11
* https://github.com/mozilla/fxa-auth-db-mysql/pull/7
* https://github.com/mozilla/fxa-js-client/pull/141
* https://github.com/mozilla/fxa-content-server/pull/1806
* https://github.com/mozilla/fxa-auth-server/pull/867
=> add unlock email

.eslintrc, .travis.yml, Gruntfile.js, bin/server.js, package.json, tasks/eslint.js, templates/index.js, test/local/translator_tests.js, test/mail_helper.js, translator.js
Fixes #45
Add ESLint and remove lint errors
@pdehaan
=> chore(lint): add ESLint to repo

mailer.js
@rfk - I promised it immediately. Here ya go.
This is running on stomlinson.dev.lcip.org
=> refactor(mailer): Extract boilerplate sending code into send.

README.md
=> chore(l10n): document the new l10n extraction workflow

templates/verify.html, templates/verify.txt
Finally got this thing humming!
Here's a bunch of screenshots of how it looks everywhere: 
https://www.dropbox.com/sh/08l1mgm583tc746/AACJyIfyyvwkAygDMKtsR0rza?dl=0
@ryanfeeley
=> style(verify): add logo and restyle verify email

templates/verify.html
@rfk let me run this through our testing service before merge
=> fix(schema): re-add schema html

templates/_pending.txt, templates/post_verify.txt, templates/reminder.txt
@ryanfeeley please activate... *er* verify these strings are correct as written.
Closes #69
=> stubbed post_verify and reminder email text

config.js, mailer.js, package.json, templates/_pending.txt, templates/index.js, templates/new_sync_device.html, templates/new_sync_device.txt, templates/password_changed.html, templates/password_changed.txt, templates/password_reset.html, templates/password_reset.txt, templates/post_verify.html, templates/post_verify.txt, templates/reminder.txt, templates/reset.txt, templates/unlock.html, templates/unlock.txt, templates/verification_reminder.html, templates/verification_reminder.txt, templates/verify.html, templates/verify.txt
Sorry for jamming these all into one, but it made extracting strings easier.
#51
#60 
#62 
#68
#66 
#65
=> added post verify and reminder emails +housekeeping

templates/verify.html
=> maybe fix #73

mailer.js
=> fix(email): adjust sign-in subject to include Firefox instead of sync

config.js
=> feat(support): better support page and a new support url

partials/verify_reminder_first.html, partials/verify_reminder_second.html, templates/verify_reminder_first.html, templates/verify_reminder_second.html
=> feat(reminder): add verification reminder email templates and strings

.gitignore, .travis.yml, log.js, mailer.js, package.json, test/local/mailer_tests.js
=> fix(deps): update dependencies

.travis.yml
=> chore(travis): run grunt l10n-extract on travis

config.js, lib/crypto/butil.js, lib/db.js, lib/pool.js, lib/promise.js, package.json, test/local/db_tests.js, test/local/pool_tests.js, test/test_server.js
=> feat(db): add ability to check account verification status

mailer.js, test/local/mailer_tests.js
=> feat(email): add utm params to the post verify email

config.js, mailer.js, partials/password_reset.html, partials/reset.html, templates/password_reset.html, templates/password_reset.txt, templates/reset.html, templates/reset.txt
This PR updates password flow email templates. 
Reference https://github.com/mozilla/fxa-content-server/issues/3467
Reference https://github.com/mozilla/fxa-content-server/pull/3559
=> feat(styles): Update password reset templates

config.js
Should match: https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L371
@rfk @vbudhram r?
=> fix(config): add content server config values

package.json
=> fix(install): Update grunt to fix peerDependency problem on install

index.js, mailer.js, package.json, templates/index.js, templates/password_reset_required.html, templates/password_reset_required.txt, templates/suspicious_location.html, templates/suspicious_location.txt, test/local/mailer_tests.js
New templates:
* suspicious location
* reset_password_required
Add the ability to pass in a "sender" to the Mailer, for testing.
=> feat(mailer): Add new security templates

config.js, mailer.js, partials/verify_login.html, templates/index.js, templates/verify_login.html, templates/verify_login.txt, test/local/mailer_tests.js
This PR contains the re-verify email template. Based on the original verify email template.
=> feat(security): signin confirmation email

Gruntfile.js
Fixes: https://github.com/mozilla/fxa-content-server/issues/3612
Ref: https://github.com/zaach/jsxgettext/pull/106
=> fix(l10n): adjust l10n-extract keyword

.travis.yml, scripts/start-travis-auth-db-mysql.sh
=> fix(travis): update Travis to MySql 5.6

partials/base/base.html, partials/base/base_text_only.html, partials/password_reset.html, partials/post_verify.html, partials/reset.html, partials/unlock.html, partials/verify.html, partials/verify_login.html, templates/new_device_login.html, templates/new_device_login.txt, templates/password_changed.html, templates/password_changed.txt, templates/password_reset.html, templates/password_reset.txt, templates/password_reset_required.txt, templates/post_verify.html, templates/post_verify.txt, templates/reset.html, templates/reset.txt, templates/suspicious_location.txt, templates/unlock.html, templates/unlock.txt, templates/verification_reminder_first.html, templates/verification_reminder_first.txt, templates/verification_reminder_second.html, templates/verification_reminder_second.txt, templates/verify.html, templates/verify.txt, templates/verify_login.html, templates/verify_login.txt
=> feat(mail): Add the Mozilla address to all emails.

mailer.js, partials/verify_login.html, templates/verify_login.html, templates/verify_login.txt, test/local/mailer_tests.js
Also remove `passwordChangeLinkAttributes` from all emails that do not
use them.
@vbudhram - r?
=> fix(mailer): Add change password link to "Verify login" email

partials/verification_reminder_second.html, templates/verification_reminder_second.html, templates/verification_reminder_second.txt
fixes #152
@ryanfeeley and @vladikoff - r?
=> fix(mail): Shorten the "Still there?" text.

config.js
=> feat(config): update confirmation links to store listings

.gitignore, Gruntfile.js, package.json, scripts/write-to-disk.js, tasks/eslint.js
=> feat(mailer): Add the `write-to-disk.js` script.

mailer.js
=> feat(metrics): track templates used in sent email

bin/server.js, config.js, config/dev.json, lib/db.js, lib/pool.js, lib/verification-reminders.js, mailer.js, test/helpers.js, test/local/reminder_db_tests.js, test/local/reminder_tests.js
=> feat(reminders): add verification reminders

scripts/.eslintrc, scripts/rpm-version.js, scripts/write-to-disk.js
=> chore(eslint): make eslint rules consistent

bin/server.js, config.js, lib/db_connect.js, test/local/db_connect_tests.js
=> feat(server): add db connection retry on start

npm-shrinkwrap.json, package.json
=> fix(deps): update dev dependencies

translator.js
Fixes #192 
@vbudhram better fix for #192
=> fix(mailer): fix undefined translation choice

templates/new_device_login.txt
=> fix(style): Change to supported apostrophe

npm-shrinkwrap.json, package.json
=> fix(deps): update to poolee 1.0.1

bin/server.js, config.js, lib/verification-reminders.js, npm-shrinkwrap.json, package.json, test/local/reminder_tests.js
As a start, I have these changes to get this ready for production. There will probably be other changes later, but this is a first set.
1. dump the full config at startup.
2. errors should be logged at error level.
3. Use language list from fxa-shared.
r? - @vladikoff
=> changes to make this ready for production

mailer.js
=> fix(send): improve error logging

mailer.js, test/local/mailer_tests.js
=> feat(headers): Add email template name to headers sent

partials/location/location.html, partials/new_device_login.html, partials/verify_login.html, templates/new_device_login.html, templates/new_device_login.txt, templates/verify_login.html, templates/verify_login.txt
Extract the common stuff to partials so it's easier to change from
now on.
fixes #216 
@vbudhram - mind an r?
note to @shane-tomlinson - update the template in #198 to use the partial.
=> fix(mailer): Swap the order of IP and Location.

.travis.yml, package.json, scripts/tap-coverage.js
Noticed test coverage wasn't being reported for this. Uses the common coverage script.
=> fix(coverage): Add script to enabled code coverage for local tests

.travis.yml
fix(travis): test on node 4 and 6; always CXX=g++-4.8
r? - @vladikoff
=> fix(travis): test on node 4 and 6; always CXX=g++-4.8

config.js, mailer.js, partials/unblock_code.html, scripts/write-to-disk.js, templates/index.js, templates/unblock_code.html, templates/unblock_code.txt, test/local/mailer_tests.js
=> feat(mailer): Add signin authorization and support.

test/local/db_tests.js, test/local/legacy_log_tests.js, test/local/mailer_tests.js
=> fix(tests): increase testing coverage

config.js
=> fix(config): add extra validation for supported locales

README.md, npm-shrinkwrap.json, package.json, scripts/download_l10n.sh
=> fix(l10n): update l10n SHA handling

config.js, mailer.js, test/local/mailer_tests.js
This (along with changes to come for fxa-auth-server, and config changes in AWS), will provide more fine-grained details on SES usage.
r? - @vladikoff, @vbudhram
=> set up "SES Event Publishing" metrics

partials/location/location.html, templates/new_device_login.html, templates/password_changed.html, templates/recovery.html, templates/unblock_code.html, templates/verify_login.html, templates/verify_sync.html
All emails that have location details updated per https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit
Sample:
Fixes #246
=> refactor(templates): Update to correct details styling

mailer.js, partials/base/base.html, partials/base/base_text_only.html, partials/location/location.html, partials/password_changed.html, partials/password_reset.html, partials/post_verify.html, partials/recovery.html, partials/unblock_code.html, partials/verify.html, partials/verify_login.html, partials/verify_sync.html, templates/new_device_login.html, templates/password_changed.html, templates/password_reset.html, templates/post_verify.html, templates/recovery.html, templates/unblock_code.html, templates/verification_reminder_first.html, templates/verification_reminder_second.html, templates/verify.html, templates/verify_login.html, templates/verify_sync.html
Easiest way to test is to run `node ./scripts/write-to-disk.js all` and view html output in `.mail_output` folder.
Fixes #242
Sample Emails
=> refactor(templates): Update to correct font-size and line height

config.js
@vbudhram r?
This change because all auth-servers will be polling and not just one.
=> fix(config): change reminder poll for many servers

config.js, mailer.js, test/local/mailer_tests.js
=> fix(mail): add from header for the new nodemailer
