- config.js
This updates the defailt sender to match what's suggested in https://github.com/mozilla/fxa-auth-server/issues/841#issuecomment-75295048
I'm not sure if this local config value is actually used in our current setup, but it seems wise to keep things consistent.  @dannycoates r?
> Use new, shorter sender address on verification emails

- Gruntfile.js
Look in the .js files for strings surrounded by `gettext()`
fixes #31
> fix(l10n): Ensure the email subjects are extracted.

- mailer.js
in local development, I've updated `/fxa-auth-server/config/dev.json`. adding into smtp, `user` and `password` as they are by default `undefined` (trying to use smtp from Gandi.net)
but I've received `RecipientError` `Client host rejected: Access denied` by the server
Then I saw that these prop in config are not used in nodemailer when it is called.. that's why I've added the `auth` config.
> add auth obj in options if set in config

- config.js
- index.js
- test/local/translator_tests.js
- translator.js
This adjusts the defaultLanguage from 'en-US' to 'en' and makes that sorta configurable. 
I don't particularly like the `config.i18n` part, since that's a detail from fxa-auth-server.
> fix(l10n): make defaultLanguage configurable, and switch to "en" default

- package.json
specifying the type and URL is deprecated:
https://docs.npmjs.com/files/package.json#license
> chore(license): Update license attribute to be SPDX compliant

- translator.js
So this fixes the issue noted in https://github.com/mozilla/fxa-auth-mailer/pull/46#issuecomment-111657709 and https://github.com/mozilla/fxa-content-server-l10n/issues/52
(This whole 'upper-case or lower-case', '- or _', '2 or 3 or 4 character' language and/or country-code is fugly).
> fix(locales): always normalize the locale

- config.js
- mailer.js
- templates/index.js
- templates/new_sync_device.html
- templates/new_sync_device.txt
- templates/password_changed.html
- templates/password_changed.txt
- templates/password_reset.html
- templates/password_reset.txt
fixes #24
Link to:
https://github.com/mozilla/fxa-js-client/pull/146
https://github.com/mozilla/fxa-auth-server/pull/876
https://github.com/mozilla/fxa-auth-server/pull/941
https://github.com/mozilla/fxa-content-server/pull/2129
https://github.com/mozilla/fxa-content-server/pull/2561
https://github.com/mozilla/fxa-content-server/pull/2562
> feat: Add change password, reset password, and new sync device notification emails.

- mailer.js
- templates/verify.html
Fixes https://github.com/mozilla/fxa-auth-mailer/issues/36.
Right now to test it you have to copy-paste the email HTML code [here](http://gmail-actions.appspot.com/).
I think maybe @jrgm will have to [register to Google](https://developers.google.com/gmail/markup/registering-with-google) to make it work on production servers.
> feat(signup): add schema.org one-click-action button to verify email

- templates/reset.html
- templates/reset.txt
Fixes https://github.com/mozilla/fxa-auth-server/issues/881.
That issue only mentions the buttons, so I've not made the change in the text templates. Is that right/wrong?
> Append "now" to verify/reset password button CTAs

- templates/post_verify.html
> fix(templates): disable HTML escaping of Android/iOS product links.

- templates/new_sync_device.html
- templates/password_changed.html
- templates/password_reset.html
- templates/post_verify.html
- templates/reset.html
- templates/unlock.html
- templates/verification_reminder.html
- templates/verify.html
> fix(templates): remove extra alt text from the Firefox logo

- mailer.js
- partials/base/base_text_only.html
- partials/post_verify.html
- partials/reset.html
- partials/unlock.html
- partials/verification_reminder.html
- partials/verify.html
- templates/new_sync_device.html
- templates/password_changed.html
- templates/password_reset.html
- templates/post_verify.html
- templates/reset.html
- templates/unlock.html
- templates/verification_reminder.html
- templates/verify.html
- test/local/mailer_tests.js
Fixes #74 
@dannycoates r?
When merging the next batch of extracted strings, we'll need to convert/regex-foo the old stings into this new format so we don't lose any translations.
> fix(l10n): remove html attributes from string

- mailer.js
- partials/base/base_text_only.html
- templates/new_sync_device.html
- templates/password_changed.html
- templates/password_reset.html
- test/local/mailer_tests.js
> fix(email): add better password change link for certain emails

- config.js
Not sure why the l10n-extract task chokes on `const` keyword, but the world is a funny place.
```sh
➜  fxa-auth-mailer git:(issue-114) $ grunt l10n-extract
Running "l10n-extract" task
Done, without errors.
$ node --version && npm --version
v0.10.35
2.14.2
```
Fixes #114
> fix(l10n): Convert const to var to fix l10n-extract Grunt task

- package.json
Picks up this fix for exception logging - https://github.com/mozilla/mozlog/commit/e11def164c2a8cf2578930227815bea01c90b799
> chore(dependencies): upgrade mozlog to 2.0.3

- bin/server.js
Fetch the port from config using `config.get('port')` instead of `config.port`.
fixes #136
> fix(server): Fix the port binding.

- mailer.js
- partials/password_changed.html
- partials/password_reset.html
- partials/post_verify.html
- templates/password_changed.html
- templates/password_changed.txt
- templates/password_reset.html
- templates/password_reset.txt
- templates/post_verify.html
- templates/reset.txt
- test/local/mailer_tests.js
* Password changed template shows "reset your password" link. "change your password" used to be displayed. If an attacker changed the user's password, the user would not know the new password to change it.
* Fix the "reset password" link color in the "Your password has been reset" email.
* All password reset links auto-submit the password reset form.
* The "Change your password" link in the "New sign in to Firefox" email contains the users email address.
fixes #151
fixes #153
fixes #154
fixes #155
fixes #157
> fix(mailer): Several mailer fixes

- mailer.js
- test/local/mailer_tests.js
@rfk r?
This will allow us to track verification flow via reminders on the auth-server
ref https://github.com/mozilla/fxa/issues/138
> feat(metrics): include type of reminder in the email query

- Gruntfile.js
- grunttasks/bump.js
- grunttasks/changelog.js
- grunttasks/eslint.js
- grunttasks/l10n-extract.js
- grunttasks/lint.js
- grunttasks/templates.js
- grunttasks/version.js
- npm-shrinkwrap.json
- package.json
Per @jrgm's request at [1], this adds our usual grunt scripting for tagging releases, making it easier to deploy this as a standalone server instead of a library.  @vladikoff r?
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1281355#c2
> Grunt release scripting

- scripts/rpm-version.js
Error is handled by defaulting to empty stdout. So unlikely to actually fail.
Merging to fix master.
> fix(eslint): in this case, yes, we do just ignore the error

- bin/server.js
- config.js
The default binding should be localhost; not a public endpoint, right? 
r? - @vladikoff
> fix(bind): should by default bind to localhost

- config/dev.json
This fixes the content-server functional tests for unverified accounts. The
verification reminder emails arrived before sign in w/ an unverified account
verification emails.
fixes mozilla/fxa-content-server#3929
@vladikoff - r? ~~Can you hold off on merging, I want to make sure this really does what it says it does.~~
> fix(mailer): Slow down the verification reminder emails in dev.

- .gitignore
- mailer.js
- test/local/mailer_tests.js
> feat(geo): add state info into emails

- partials/password_reset.html
- partials/recovery.html
- templates/password_reset.html
- templates/recovery.html
Change both "password_reset" and "recovery" to use `h1` instead of `h3`
fixes #217 
@ryanfeeley - r?
> fix(mailer): Fix the title size in the password reset related templates.

- mailer.js
- partials/post_verify.html
- partials/recovery.html
- partials/verify.html
- partials/verify_login.html
- templates/post_verify.html
- templates/recovery.html
- templates/verification_reminder_first.html
- templates/verification_reminder_second.html
- templates/verify.html
- templates/verify_login.html
- test/local/mailer_tests.js
It's big. It detracts from the main link. It's so big that it's
impossible to place other content below it. @ryanfeeley wants it out!
fixes #228
@vbudhram - r?
> feat(mailer): Remove the `Alternatively` link from all emails.

- mailer.js
- test/local/mailer_tests.js
> refactor(mailer): Increase comprehensibility of device description

- config.js
- lib/verification-reminders.js
r? - @vladikoff or @jbuck 
The database queries are extremely unfriendly to mysql replication. I have disabled `verificationReminders.rate` in the auth-server, but I'd like a graceful way to disable this polling entirely today, and we can revisit what other changes are needed on Monday.
> fix(config): disable polling if pollTime === 0

- mailer.js
- test/local/mailer_tests.js
This PR adds support for forwarding the `flowId` and `flowBeginTime` values in the email headers. These will be used to track email bounce events that correspond to flows. This has been added to all our emails except `verificationReminderEmail`.
Part of https://github.com/mozilla/fxa-auth-server/issues/1425
> fix(metrics): Add flowId and flowBeginTime to headers if avalible

- mailer.js
- partials/base/base.html
- partials/location/location.html
- partials/password_changed.html
- partials/recovery.html
- partials/verify_sync.html
- templates/index.js
- templates/new_device_login.html
- templates/password_changed.html
- templates/password_changed.txt
- templates/password_reset.html
- templates/post_verify.html
- templates/recovery.html
- templates/unblock_code.html
- templates/verification_reminder_first.html
- templates/verify.html
- templates/verify_login.html
- templates/verify_sync.html
- templates/verify_sync.txt
- test/local/mailer_tests.js
This PR adds adds a new verify account sync template. This does not change the verify account email for non-sync users. It also adds location data to
- verify sync account email
- password reset email
- password change success email
It also contains some slight text tweaks to the emails.
Fixes #189
> refactor(templates): Add more location data to emails

- AUTHORS
updating authors, but also checking of l10n extract fail was caused by deps updates or something else: 
https://github.com/mozilla/fxa-auth-mailer/pull/251
> chore(docs): update AUTHORS file

- lib/db_connect.js
- mailer.js
- npm-shrinkwrap.json
- package.json
Code changes were due to updates in bluebird, it no longer uses `cancellable`, but it's easy enough to just have a local variable track that.
> fix(dependencies): update bluebird, nodemailer, convict, moment-timezone

- index.js
- lib/sms.js
- npm-shrinkwrap.json
- package.json
- scripts/write-to-disk.js
- templates/index.js
- templates/sms.installFirefox.txt
- test/local/sms_tests.js
Related to mozilla/fxa-auth-server#1628. Replaces #254.
This is broadly the same as the previous PR. The main difference is that I didn't realise the auth server invokes the mailer in-process before, so some redundant server nonsense has been removed. For the same reason, the interface for the package needed changing to return the `sms` module. I opted to return an object `{ email, sms }` but am open to other suggestions if anyone finds that offensive.
With the elimination of my imaginary server boundary, it made sense to pull the config and phone number validation up to the auth server level so those are both removed. And with the config gone, the `send-sms` script has moved over there too.
All that means the code here should be a bit simpler than it was. I think it's ready for review …
> feat(mailer): add support for sending SMS messages
